byuing="noone"                              //×òî ìîæíî êóïèòü íàæàâ íà ýòó êíîïêó.
price=0;                                    //Öåíà.
buyunits=0;                                 //Êîë-âî âåùåé íà ïîêóïêó.
type:="noone"                               //Òèï ïðîäàâàåìûõ ïðåäìåòîâ.
spec_index:=0;                              //Ñïåö. èíäåêñ ïðîä. ïðåäìåòà.
alarm[0]=1;                            
alarm[1]=1;
image_speed=0;
cost_qty=0;
cost_type="";
cost_label=""
content="";
name="";
category="";
clickable=true;
selected=false;