var a;
ini_open(global.language_file)
a="Text Error";
new_game                    =ini_read_string("Main Menu","new_game"                     ,a);
continue_game               =ini_read_string("Main Menu","continue_game"                ,a);
compile_butt                =ini_read_string("Main Menu","compile_button"               ,a);
version_reason              =ini_read_string("Main Menu","version_reason"               ,a);
no_save                     =ini_read_string("Main Menu","no_save"                      ,a);
load_text                   =ini_read_string("Main Menu","load_text"                    ,a);
compile_text                =ini_read_string("Main Menu","compile_text"                 ,a);
compile_no_save             =ini_read_string("Main Menu","compile_no_save"              ,a);
compile_succ                =ini_read_string("Main Menu","compile_succ"                 ,a);
compile_cor_save            =ini_read_string("Main Menu","compile_cor_save"             ,a);
compile_part_error          =ini_read_string("Main Menu","compile_part_error"           ,a);
new_game_sms                =ini_read_string("Main Menu","new_game_sms"           ,a);
new_game_sure               =ini_read_string("Main Menu","new_game_sure"           ,a);
resourse_load               =ini_read_string("Main Menu","resourse_load"           ,a);
data_not_found              =ini_read_string("Main Menu","data_not_found"           ,a);
save_corrupt                =ini_read_string("Main Menu","save_corrupt",a);
MMO                         =ini_read_string("Corporation Button","MMO",a);
EIC                         =ini_read_string("Corporation Button","EIC"                 ,a);
VRU                         =ini_read_string("Corporation Button","VRU"                 ,a);
are_you_sure                =ini_read_string("Corporation Button","are_you_sure"        ,a);
compile_choose              =ini_read_string("Corporation Button","choose"              ,a);
nick_change                 =ini_read_string("Button","nick_change"                     ,a);
nick_change_sms             =ini_read_string("Button","nick_change_sms"          ,a);
nick_change_sms_succes      =ini_read_string("Button","nick_change_sms_succes"          ,a);
nick_change_sms_fail        =ini_read_string("Button","nick_change_sms_fail"            ,a);
corp_change                 =ini_read_string("Button","corp_change"                     ,a);
corp_change_sms             =ini_read_string("Button","corp_change_sms"          ,a);
corp_change_sms_succes      =ini_read_string("Button","corp_change_sms_succes"          ,a);
corp_change_sms_fail        =ini_read_string("Button","corp_change_sms_fail"            ,a);
mob_destroy                 =ini_read_string("Game","mob_destroy"                 ,a);
ship_dead                   =ini_read_string("Game","ship_dead"                 ,a);
target_in_security          =ini_read_string("Game","target_in_security"          ,a);
no_ammo                     =ini_read_string("Game","no_ammo"          ,a);
no_gun                      =ini_read_string("Game","no_gun"          ,a);
target_lenght_out           =ini_read_string("Game","target_lenght_out"          ,a);
target_is_ally              =ini_read_string("Game","target_is_ally"          ,a);
radiation_warning           =ini_read_string("Game","radiation_warning"          ,a);
stars_on                    =ini_read_string("Game","stars_on"          ,a);
stars_off                   =ini_read_string("Game","stars_off"          ,a);
sound_on                    =ini_read_string("Game","sound_on"          ,a);
sound_off                   =ini_read_string("Game","sound_off"          ,a);
box_grub_x4ammo             =ini_read_string("Game","box_grub_x4ammo"          ,a);
box_grub_details            =ini_read_string("Game","box_grub_details"          ,a);
no_teleport_pvp             =ini_read_string("Game","no_teleport_pvp"          ,a);
bonus_grub_money            =ini_read_string("Game","bonus_grub_money"          ,a);
bonus_grub_ammo             =ini_read_string("Game","bonus_grub_ammo"          ,a);
bonus_grub_rocket           =ini_read_string("Game","bonus_grub_rocket"          ,a);
destroy_save                =ini_read_string("Game","destroy_save"          ,a);
destroy_unsave              =ini_read_string("Game","destroy_unsave"          ,a);
money_text                  =ini_read_string("HUD","money"          ,a);
ammo_text                   =ini_read_string("HUD","ammo"          ,a);
rocket_text                 =ini_read_string("HUD","rocket"          ,a);
ammo_text                   =ini_read_string("HUD","ammo"          ,a);
health_text                 =ini_read_string("HUD","health"          ,a);
shield_text                 =ini_read_string("HUD","shield"          ,a);
security_zone               =ini_read_string("HUD","security_zone"          ,a);
map_minimap                 =ini_read_string("HUD","map_minimap"          ,a);
on_fire                     =ini_read_string("HUD","on_fire"          ,a);
max_droid_sms               =ini_read_string("Menu","max_droid_sms"          ,a);
service_not_available       =ini_read_string("Menu","service_not_available"          ,a);
review_sms                  =ini_read_string("Menu","review_sms"          ,a);
rep_card_sms                =ini_read_string("Menu","rep_card_sms"          ,a);
buy                         =ini_read_string("Menu","buy"          ,a);
cancel                      =ini_read_string("Menu","cancel"          ,a);
rep_card_succes             =ini_read_string("Menu","rep_card_succes"          ,a);
ammo_buy                    =ini_read_string("Menu","ammo_buy"          ,a);
rocket_buy                  =ini_read_string("Menu","rocket_buy"          ,a);
buy_tnx                     =ini_read_string("Menu","buy_tnx"          ,a);
no_space_buy                =ini_read_string("Menu","no_space_buy"          ,a);
engine_sms                  =ini_read_string("Menu","engine_sms"          ,a);
engine_sms_buy              =ini_read_string("Menu","engine_sms_buy"          ,a);
sms_buy_count               =ini_read_string("Menu","sms_buy_count"          ,a);
shield_sms                  =ini_read_string("Menu","shield_sms"          ,a);
design_goliath_sms          =ini_read_string("Menu","design_goliath_sms"          ,a);
design_buy                  =ini_read_string("Menu","design_buy"          ,a);
set_set                     =ini_read_string("Menu","set_set"          ,a);
design_set                  =ini_read_string("Menu","design_set"          ,a);
ship_buy_sms                =ini_read_string("Menu","ship_buy_sms"          ,a);
ship_buy_sure               =ini_read_string("Menu","ship_buy_sure"          ,a);
ship_buy_succes             =ini_read_string("Menu","ship_buy_succes"          ,a);
ship_buy_yes                =ini_read_string("Menu","ship_buy_yes"          ,a);
droid_sms                   =ini_read_string("Menu","droid_sms"          ,a);
droid_sms_sure              =ini_read_string("Menu","droid_sms_sure"          ,a);
gun_sms                     =ini_read_string("Menu","gun_sms"          ,a);
no_space_invent             =ini_read_string("Inventory","no_space_invent"          ,a);
no_space_invent2            =ini_read_string("Inventory","no_space_invent+"          ,a);
no_space_droid              =ini_read_string("Inventory","no_space_droid"          ,a);
no_space_ship               =ini_read_string("Inventory","no_space_ship"          ,a);
engine_to_droid             =ini_read_string("Inventory","engine_to_droid"          ,a);
item_to_reserv              =ini_read_string("Inventory","item_to_reserv"          ,a);
item_invent_menu_ship       =ini_read_string("Inventory","item_invent_menu_ship"          ,a);
item_invent_menu_droid      =ini_read_string("Inventory","item_invent_menu_droid"          ,a);
item_on_ship_menu           =ini_read_string("Inventory","item_on_ship_menu"          ,a);
droid_menu                  =ini_read_string("Inventory","droid_menu"          ,a);
item_sell_sms               =ini_read_string("Inventory","item_sell_sms"          ,a);
ship_sms_inv                =ini_read_string("Inventory","ship_sms_inv"          ,a);
droid_sms_inv               =ini_read_string("Inventory","droid_sms_inv"          ,a);
reserv_sms_inv              =ini_read_string("Inventory","reserv_sms_inv"          ,a);
next_page                   =ini_read_string("Inventory","next_page"          ,a);
prev_page                   =ini_read_string("Inventory","prev_page"          ,a);
to_inventory                =ini_read_string("Inventory","to_inventory"          ,a);
to_ship                     =ini_read_string("Inventory","to_ship"          ,a);
to_droid                    =ini_read_string("Inventory","to_droid"          ,a);
type_sms                    =ini_read_string("Inventory","type_sms"          ,a);
type_gun                    =ini_read_string("Inventory","type_gun"          ,a);
type_engine                 =ini_read_string("Inventory","type_engine"          ,a);
type_shield                 =ini_read_string("Inventory","type_shield"          ,a);
type_droid                  =ini_read_string("Inventory","type_droid"          ,a);
damage_sms                  =ini_read_string("Inventory","damage_sms"          ,a);
power_sms                   =ini_read_string("Inventory","power_sms"          ,a);
block_percent_sms           =ini_read_string("Inventory","block_percent_sms"          ,a);
speed_inv_sms               =ini_read_string("Inventory","speed_inv_sms"          ,a);
numb_slots                  =ini_read_string("Inventory","numb_slots"          ,a);
cost_sms                    =ini_read_string("Inventory","cost_sms"          ,a);
reserv_empty_text           =ini_read_string("Inventory","reserv_empty_text"          ,a);
reserv_fill_text            =ini_read_string("Inventory","reserv_fill_text"          ,a);
guns_string                 =ini_read_string("Inventory","guns_string"          ,a);
shield_string               =ini_read_string("Inventory","shield_string"          ,a);
engine_string               =ini_read_string("Inventory","engine_string"          ,a);
inventory_string            =ini_read_string("Inventory","inventory_string"          ,a);
Exit                        =ini_read_string("Other","Exit"                             ,a);
help                        =ini_read_string("Other","help"                             ,a);
//help+="##-=Àâòîðû=-##Àâòîð(Author):#Äàíèëà Êëèíîâ (Danila Klinov). Òàêæå "dankl96" èëè "-=Ä=À=Í=È=Ë=À=-" â îðèãèíàëüíîì ÄÎ.##Ñàéò ïðîåêòà(Project Web-Site): http://darkorbit-remix.ucoz.ru/"
no_money                    =ini_read_string("Other","no_money"                         ,a);
//----------------------------------------------------------------------------------------------
//Custom entries
//Rankpoints
rankpointcount              =ini_read_string("rankpoints","rankpointcount"              ,a)
rankpointsare               =ini_read_string("rankpoints","rankpointsare"              ,a)
rpcalculated                =ini_read_string("rankpoints","rpcalculated"              ,a)
//level,ep,honor
level                       =ini_read_string("othershud","level"              ,a)
experience                  =ini_read_string("othershud","experience"              ,a)
honor                       =ini_read_string("othershud","honor"              ,a)
//cloak
boughtcloak                 =ini_read_string("cloak","boughtcloak"              ,a)
failedtobuycloak            =ini_read_string("cloak","failedtobuycloak"              ,a)
alreadycloaked              =ini_read_string("cloak","alreadycloaked"              ,a)
//fighting
targetinsafezone            =ini_read_string("fighting","targetinsafezone"              ,a)
norsb                       =ini_read_string("fighting","norsb"              ,a)
cannotattackally            =ini_read_string("fighting","cannotattackally"              ,a)
emprecharging               =ini_read_string("fighting","emprecharging"              ,a)
noemps                      =ini_read_string("fighting","noemps"              ,a)
ishrecharging               =ini_read_string("fighting","ishrecharging"              ,a)
noishs                      =ini_read_string("fighting","noishs"              ,a)
dcrrecharging               =ini_read_string("fighting","dcrrecharging"              ,a)
nodcr                       =ini_read_string("fighting","nodcr"              ,a)
//admin
noadmin                     =ini_read_string("admin","noadmin"              ,a)
adminon                     =ini_read_string("admin","adminon"              ,a)
adminoff                    =ini_read_string("admin","adminoff"              ,a)
adminmodeisdisabled         =ini_read_string("admin","adminmodeisdisabled"              ,a)
adminspeed                  =ini_read_string("admin","adminspeed"              ,a)
//techs
eleechon                    =ini_read_string("techs","eleechon"              ,a)
eleechoff                   =ini_read_string("techs","eleechoff"              ,a)
//galaxygates
clickgates                  =ini_read_string("galaxygates","clickgates"              ,a)
clickcost                   =ini_read_string("galaxygates","clickcost"              ,a)
galaxygates                 =ini_read_string("galaxygates","galaxygates"              ,a)
alphacompleted              =ini_read_string("galaxygates","alphacompleted"              ,a)
betacompleted               =ini_read_string("galaxygates","betacompleted"              ,a)
gammacompleted              =ini_read_string("galaxygates","gammacompleted"              ,a)
deltacompleted              =ini_read_string("galaxygates","deltacompleted"              ,a)
ggdisabled                  =ini_read_string("galaxygates","ggdisabled"              ,a)
//hangar
overview                    =ini_read_string("hangar","overview"              ,a)
hangar                      =ini_read_string("hangar","hangar"              ,a)
ship_buy                    =ini_read_string("hangar","ship_buy"              ,a)
skilltree                    =ini_read_string("hangar","skilltree"              ,a)
drone_buy                   =ini_read_string("hangar","drone_buy"              ,a)
buy_lasers                  =ini_read_string("hangar","buy_lasers"              ,a)
buy_ammo                    =ini_read_string("hangar","buy_ammo"              ,a)
buy_generator               =ini_read_string("hangar","buy_generator"              ,a)
buy_extras                  =ini_read_string("hangar","buy_extras"              ,a)
buy_designs                 =ini_read_string("hangar","buy_designs"              ,a)
//others
settingsmenu                =ini_read_string("others","settingsmenu"              ,a)
enabled                     =ini_read_string("others","enabled"              ,a)
disabled                    =ini_read_string("others","disabled"              ,a)
received                    =ini_read_string("others","received"              ,a)
nojumpcpu                   =ini_read_string("others","nojumpcpu"              ,a)
entercheat                  =ini_read_string("others","entercheat"              ,a)
entershipname               =ini_read_string("others","entershipname"              ,a)
droneerror                  =ini_read_string("others","droneerror"              ,a)
nocheat                     =ini_read_string("others","nocheat"              ,a)
changemoney                 =ini_read_string("others","changemoney"              ,a)
jpacompleted                =ini_read_string("others","jpacompleted"            ,a)
//New patch 5.1.1
warreprecharging            =ini_read_string("techs","warreprecharging"     ,a)
nowarreps                   =ini_read_string("techs","nowarreps",       a)
shieldbackuprecharging      =ini_read_string("techs","shieldbackuprecharging",      a)
noshieldbackups             =ini_read_string("techs","noshieldbackups",     a)
//New rev 5.3
no_moneyURI                 =ini_read_string("patch53","no_uridium"                         ,a)
buy_booster                 =ini_read_string("patch53","buy_booster",           a)
buy_level                   =ini_read_string("patch53","buy_level",             a)
failed_to_buy_level         =ini_read_string("patch53","failed_to_buy_level",   a)
ini_close();
show_debug_message("Òåêñò çàãðóæåí")