owner=noone;                      //"Õîçÿèí" ñíàðÿäà.
damage=10;
damage_x=1;                        //Óðîí.
target:=noone;                    //Öåëü ïàòðîíà.
//alarm[0]=room_speed*1.2;
speedrocket=22;
premium_lasers=false;
drawDamage=true;
targetx:=mouse_x;
targety:=mouse_y;
xowner:=gamer.x;
yowner:=gamer.y;
final_targetx=0;
final_targety=0;
x0=0;
y0=0;
depth = gamer.depth+1
target=0;
critical_hit = false;
ownership=0;
restoredHP=0;
image_alpha=0;
image_speed=0;
image_xscale = 1.1;//global.scale;
image_yscale = 1.1;//global.scale;
sprite_index=new_laser_spr;
level=0;
targetedship=0;
ammoangle=0;
decrease_angle_factor=0.9999;
if instance_exists(gamer.target) then targetedship:=gamer.target;
alarm[4] = 1; //crit hit etc init