corporation:=4;                 //Êîðïîðàöèÿ :D Íà ñàìîì äåëå äëÿ ñîâìåñòèìîñòè.
v_zone_bz=false;                //Íàõîäèòñÿ ëè ìîá â ÁÇ :D. Äëÿ ñîâìåñòèìîñòè.
target:=noone;                  //Öåëü ìîáà.
runing=false;                   //Áåæèò ëè ìîá.
follow[0]:=irandom(150);
follow[1]:=irandom(150);        //Ìàññèâ äëÿ ñëåäîâàíèÿ çà èãðîêîì.
lock_:=false;                   //"Çàìîê" íà öåëè.
expl_color:=false;              //Íóæíî ëè è, åñëè íóæíî, êàêèì öâåòîì ïîäêðàøèâàòü âçðûâû. (äëÿ èìèòàöèè êðîâè è ò. ä.)
expl_scale:=1;                  //Ðàçìåð âçðûâà.
wave_scale:=1;                  //Ðàçìåð óäàðíîé âîëíû.
EPPOINTS:=0;
cloaked=0;
myid=0;
target=0;
decx=32;
ish=0;
isFollower=0;
gotKilledBy=noone;
decy=60;
targetedship=0;
own_health_bilo=0;
health_def = 0;
followHP = health_def;
shield_def = 10000;
own_shield = 10000;
followShield = own_shield;
shieldAbsorb = 0.8;
shieldPen = 0.8;
attacking=false;
ship_speed=8;
sprite_index=empty_spr;
target=noone;
emp=0;
HONORPOINTS:=0;
_run_to_x = irandom_range(100, room_width-100);
_run_to_y = irandom_range(100, room_height-100);

//sprite_index=
//passive:=false;                 //Ïàññèâíûé ëè ìîá (ñëåäóåò ëè çà îáèä÷èêîì).
Loot[0,0]:=0; 
Loot[1,0]:="noone";     //×òî âûïàäàåò ñ ìîáà. [0,0] - êîë-âî âèäîâ ëóòà. [i,0] - íàçâàíèå i-ãî âèäà ëóòà,
Loot[1,1]:=0; 
depth=1;                        //"Ãëóáèíà" ìîáà (åãî ñïðàéòà).
alarm[0] = irandom_range(50,90);
alarm[1] = irandom_range(50,90);
alarm[2] = irandom_range(2,15) * room_speed;
alarm[10] = irandom_range(50,90);
